sudo: false

language: node_js
node_js:
    - "node"
    # - "4"

os:
  - linux
  # - osx

env: ELM_VERSION=0.19.0

install:
  - node --version
  - npm --version
  - npm install

script:
  - npm test
