[package]
name = "elm-test"
version = "0.18.10"
authors = ["Richard Feldman <richard.t.feldman@gmail.com>"]

[dependencies]
walkdir = "1.0.7"

[dependencies.clap]
version = "~2.26.0"
default-features = false

features = [ "suggestions", "wrap_help" ]
