[package]
name = "node-test-runner"
version = "0.1.0"
authors = ["Richard Feldman <richard.t.feldman@gmail.com>"]

[dependencies]
glob = "0.2.11"

[dependencies.clap]
version = "~2.26.0"
default-features = false

features = [ "suggestions", "wrap_help" ]
